"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# 设置为北京时间
TIME_ZONE = 'Asia/Shanghai'

# 必须启用时区支持
USE_TZ = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = 'api.Users'  # 格式: 应用名.模型名

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--2!p2dem7br52s+*)co#ny-t^0_(8r^6*1^2o33*d@lxnbx=om"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,121.196.163.155").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "channels",
    'corsheaders',
    "django.contrib.admin",
    'api',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 自定义应用

    'django_otp',
    'django_otp.plugins.otp_totp',
    'rest_framework',
    'rest_framework_simplejwt',
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

ASGI_APPLICATION = 'backend.asgi.application'

# settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.RemoteIntrospectJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.AllowAny',  # 默认允许任何请求
        "rest_framework.permissions.IsAuthenticated", 
    ],
}


# JWT设置
from datetime import timedelta
# AUTH_USER_MODEL = 'api.Users'  # 指明用户模型类
SECRET_KEY = 'SxV1X8UDIl4SEWjBw3Gx-FRbEZ01CWBHqckNRtcrKU4'  # 确保这是您的实际 SECRET_KEY

JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
JWT_SIGNING_KEY = os.getenv("JWT_SIGNING_KEY", "dev-secret-change-me")
JWT_VERIFYING_KEY = os.getenv(
    "JWT_VERIFYING_KEY",
    JWT_SIGNING_KEY if JWT_ALGORITHM == "HS256" else "",
)

SIMPLE_JWT = {
    # "USER_ID_FIELD": "userid",  # 指定用户模型中用于标识用户的字段
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),  # 设置访问令牌的有效期为60分钟
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # 设置刷新令牌的有效期为1天
    'ROTATE_REFRESH_TOKENS': False,  # 禁用刷新令牌的自动续期
    'BLACKLIST_AFTER_ROTATION': True,  # 禁用刷新令牌的黑名单功能
    'ALGORITHM': JWT_ALGORITHM,  # 指定对称加密算法
    "SIGNING_KEY": JWT_SIGNING_KEY,
    "VERIFYING_KEY": JWT_VERIFYING_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),     
}
CACHES = {
      "default": {
          "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
          "LOCATION": "auth-cache",
      }
}
AUTH_REMOTE_BASE = os.getenv("AUTH_REMOTE_BASE", "http://121.196.163.155:8080")
AUTH_REMOTE_INTROSPECT = f"{AUTH_REMOTE_BASE}/introspect/"
AUTH_REMOTE_TOKEN = os.getenv("AUTH_REMOTE_TOKEN", f"{AUTH_REMOTE_BASE}/token/")
AUTH_REMOTE_REFRESH = os.getenv("AUTH_REMOTE_REFRESH", f"{AUTH_REMOTE_BASE}/token/refresh/")
AUTH_REMOTE_MEDIA_BASE = os.getenv("AUTH_REMOTE_MEDIA_BASE", "http://121.196.163.155:8081")
AUTH_REMOTE_MEDIA_DELETE = os.getenv("AUTH_REMOTE_MEDIA_DELETE", f"{AUTH_REMOTE_MEDIA_BASE}/media/delete/")
AUTH_REMOTE_TIMEOUT = 3  # 秒，增加超时时间
AUTH_CACHE_TTL = 120  # 秒，短缓存，正负结果都会缓存，远端短暂不可用时降低误踢
# 设为 False 可在开发环境关闭远端内省，仅本地验证 JWT
AUTH_REMOTE_ENABLED = False  # 启用远端验证
JUMP_DEVICE = os.getenv("JUMP_DEVICE", "auto")


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 必须放在第一个
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'api.utils.auth.JWTAuthenticationMiddleware',
]

ROOT_URLCONF = "backend.urls"
# 允许所有来源（开发环境使用）
CORS_ALLOW_ALL_ORIGINS = True
# 4. 允许携带凭证（如 cookies）
CORS_ALLOW_CREDENTIALS = True

# 5. 允许的请求方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 6. 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-client-device',
    'x-totp-code',  # 添加自定义头部
]
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
]

# 7. 允许跨域请求的响应头
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'test_db',
#         'USER': 'herrick1',
#         'PASSWORD': '520Yhhcf',
#         'HOST': 'rm-cn-7xh499xk8000sveo.rwlb.rds.aliyuncs.com',
#         'PORT': 3306,
#         'OPTIONS': {
#             'charset': 'utf8mb4',  # 设置字符集，与你的 pymysql 配置一致
#             'init_command': "SET time_zone='+08:00'",
#         },
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'school_system',
        'USER': 'root',
        'PASSWORD': 'Zhihui123',
        'HOST': '121.196.163.155',
        'PORT': 3306,
        'OPTIONS': {
            'charset': 'utf8mb4',  # 设置字符集，与你的 pymysql 配置一致
            'init_command': "SET time_zone='+08:00'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 日志配置：默认输出 api.authentication 的 DEBUG 日志到控制台
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            'level': 'WARNING',
        },
        "auth_file": {
            "class": "logging.FileHandler",
            "filename": os.getenv("AUTH_LOG_FILE", "auth.log"),
            "encoding": "utf-8",
            'level': 'WARNING',
        },
    },
    "loggers": {
        "api.authentication": {
            "handlers": ["console", "auth_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "daphne": {
            "level": "WARNING",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            "level": "WARNING",
            "propagate": False,
        },
        "channels": {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        "asyncio": {
            "level": "WARNING",
            "propagate": False,
        },
        "matplotlib.font_manager": {
            "level": "WARNING",
            "propagate": False,
        },
        "aiortc": {
            "level": "WARNING",
            "propagate": False,
        },
        "amqp": {
            "level": "WARNING",
            "propagate": False,
        },
        "channels_rabbitmq": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "rabbitmq": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        }
    },
}
